Chore/fnd v5 upgrade
torusresearch/torus-utils-swift pull request #26
Opened 2022-05-04 08:12 UTC by dhruvTor

Error messages fix

2022-05-04 08:36 UTC, michaellee8 requested changes
@dhruv500 Please address the comments. Basically log more things, log the wider context, and don't use nil for log message, log some actual text insted. User's device may not be able to provider stacktrace and our clients won't necessarily have the time to look at those errors.

2022-05-04 08:36 UTC, michaellee8 commented on Sources/TorusUtils/Extensions/TorusUtils+extension.swift
> +                throw TorusUtilError.decodingFailed("Message value not correct or nil in \(data["message"])")
Can u log the full `data` here, the wider the context is better.

2022-05-04 08:36 UTC, michaellee8 commented on Sources/TorusUtils/Extensions/TorusUtils+extension.swift
> +                else { throw TorusUtilError.decodingFailed("keys not found in result \(decoded.result)")}
Maybe just log full decoded, here sometimes maybe result is empty.

2022-05-04 08:36 UTC, michaellee8 commented on Sources/TorusUtils/Extensions/TorusUtils+extension.swift
> +                            throw TorusUtilError.decodingFailed("\(a.result) not found")
again full `a`

2022-05-04 08:36 UTC, michaellee8 commented on Sources/TorusUtils/Extensions/TorusUtils+extension.swift
> +                    seal.reject(TorusUtilError.decodingFailed(nil))
Try to log something please, maybe log newEndpoints2

2022-05-04 10:19 UTC, dhruvTor commented on Sources/TorusUtils/Extensions/TorusUtils+extension.swift
> +                throw TorusUtilError.decodingFailed("Message value not correct or nil in \(data["message"])")
Hey @michaellee8 if you see on line 119 we are logging the data

2022-05-04 10:27 UTC, dhruvTor commented on Sources/TorusUtils/Extensions/TorusUtils+extension.swift
> +                else { throw TorusUtilError.decodingFailed("keys not found in result \(decoded.result)")}
on line 180 we are logging decoded

2022-05-04 10:28 UTC, dhruvTor commented on Sources/TorusUtils/Extensions/TorusUtils+extension.swift
> +                            throw TorusUtilError.decodingFailed("\(a.result) not found")
Done

2022-05-04 10:28 UTC, dhruvTor commented on Sources/TorusUtils/Extensions/TorusUtils+extension.swift
> +                    seal.reject(TorusUtilError.decodingFailed(nil))
Done

2022-05-04 10:32 UTC, michaellee8 commented on Sources/TorusUtils/Extensions/TorusUtils+extension.swift
> +                throw TorusUtilError.decodingFailed("Message value not correct or nil in \(data["message"])")
i meant embeding those in the errors. Sometimes the client don;t use info level logs on prod

2022-05-04 10:34 UTC, dhruvTor commented on Sources/TorusUtils/Extensions/TorusUtils+extension.swift
> +                throw TorusUtilError.decodingFailed("Message value not correct or nil in \(data["message"])")
Got it

2022-05-04 10:34 UTC, michaellee8 commented on Package.swift
> +        .package(name: "FetchNodeDetails", url: "https://github.com/torusresearch/fetch-node-details-swift.git", .branch("feat/upgradeToVersion5")),
pls rmb to fix this before merging to master

2022-05-05 04:50 UTC, michaellee8 approved these changes

2022-05-05 04:51 UTC, michaellee8 commented
lgtm except reverting https://github.com/torusresearch/torus-utils-swift/pull/26/files#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR17 before merge to master. @chaitanyapotti pls review

2022-05-05 05:27 UTC, chaitanyapotti approved these changes
lgtm

2022-05-22 10:58 UTC, merged