feat: full refactor to align torus-utils-swift to torus.js
torusresearch/torus-utils-swift pull request #97
Opened 2024-05-13 16:23 UTC by metalurgical

This PR seeks to re-align the current implementation of torus-utils-swift to that of the web implementation of torus.js.

This will reduce the overhead of differences a developer would need to remember between the two and provide an overall better experience.

This will also provide better long term maintainability and make feature parity simpler to implement between the two.

This PR should be feature-complete up until tag v12.2.0 on torus.js (commit hash: 10df43b986011a3380e782e0823139b6fed8d677)

Note this is a breaking change and needs to be released as a major version.

ToDo:
* Debug importShare
* Finish implementing tests for sapphire_mainnet, sapphire_devnet, testnet, celeste
* Remove restriction on nodeIndex == "1" for some api responses
* Return early when threshold number of responses are reached vs waiting for all.
* Remove legacy code, this is now possible due to celeste migration being completed.
* Inline documentation
* Function visibility (internal, private, public, etc)
* Update example application

2024-05-22 19:50 UTC, metalurgical commented
Closes #94

2024-05-22 20:25 UTC, metalurgical commented
Resolves #95.
Resolves #96.

2024-07-18 05:43 UTC, himanshuchawla009 requested changes

2024-07-18 05:43 UTC, himanshuchawla009 commented on Package.swift
> +        .package(url: "https://github.com/torusresearch/fetch-node-details-swift", from: "6.0.2"),
update this to latest

2024-07-18 05:43 UTC, himanshuchawla009 commented on Sources/TorusUtils/Extensions/String+Extension.swift
> +        return "0x" + self
add the hex check back

2024-07-18 05:43 UTC, himanshuchawla009 commented on Sources/TorusUtils/Extensions/String+Extension.swift
> +            finalString.append(Character(decimalString))
lets test with both odd and even length strings

2024-07-18 05:43 UTC, himanshuchawla009 commented on Sources/TorusUtils/Helpers/MetadataUtils.swift
> +        let (X, Y) = try KeyUtils.getPublicKeyCoords(pubKey: publicKey)
rather than deriving public key from oauth priv key , use threshold public key which is being sent from backend to set/get metadata nonce

2024-07-18 05:43 UTC, himanshuchawla009 commented on Sources/TorusUtils/Helpers/MetadataUtils.swift
> +            return try await getOrSetNonce(legacyMetadataHost: legacyMetadataHost, serverTimeOffset: serverTimeOffset ?? Int(trunc(Double((0) + Int(Date().timeIntervalSince1970)))), X: X, Y: Y, priva
change variable name from legacyMetadataHost to metadataHost

2024-07-18 06:02 UTC, metalurgical commented on Package.swift
> +        .package(url: "https://github.com/torusresearch/fetch-node-details-swift", from: "6.0.2"),
Sure, latest commit on fetch-node-details-swift needs to be tagged, then also released on cocoapods.

2024-07-19 06:44 UTC, himanshuchawla009 requested changes

2024-07-22 03:04 UTC, metalurgical commented on Sources/TorusUtils/Helpers/NodeUtils.swift
> +                                // extra_params: extraData
Need a list of all the available extra parameters please.

2024-07-22 06:20 UTC, himanshuchawla009 requested changes

2024-07-22 06:20 UTC, himanshuchawla009 commented on Sources/TorusUtils/TorusUtils.swift
> +                LegacyVerifierLookupResponse.Key(pub_key_X: $0.pub_key_X, pub_key_Y: $0.pub_key_Y, address: $0.address)
is this map required, plz check. if not thn remove as we are always referring to first key from the returned array

2024-07-22 06:20 UTC, himanshuchawla009 commented on Sources/TorusUtils/TorusUtils.swift
> +                if !(pubNonceResult.x.isEmpty || pubNonceResult.y.isEmpty) {
pubNonceResult x and y must be available at this point, if not we throw the error earlier

2024-07-22 06:20 UTC, himanshuchawla009 commented on Sources/TorusUtils/TorusUtils.swift
> +            nonceResult = try await MetadataUtils.getOrSetNonce(legacyMetadataHost: legacyMetadataHost, serverTimeOffset: finalServertimeOffset, X: X, Y: Y, getOnly: !isNewKey)
can we move this code inside v2 case?

2024-07-22 06:32 UTC, metalurgical commented on Sources/TorusUtils/Polynomial.swift
> +            xi = (x * tmpX).modulus(KeyUtils.getOrderOfCurve())
Yep, you are correct.

2024-07-22 06:40 UTC, metalurgical commented on Sources/TorusUtils/TorusUtils.swift
> +            nonceResult = try await MetadataUtils.getOrSetNonce(legacyMetadataHost: legacyMetadataHost, serverTimeOffset: finalServertimeOffset, X: X, Y: Y, getOnly: !isNewKey)
No, we use the nonceResult here to determine the user type, which is then used to determine whether to follow the v1 or v2 path.

The following lines are:

```
typeOfUser = UserType(rawValue: nonceResult?.typeOfUser?.lowercased() ?? "v1")!

            if typeOfUser == .v1 {
            ...
            }
```

2024-07-22 06:48 UTC, metalurgical commented on Sources/TorusUtils/TorusUtils.swift
> +                LegacyVerifierLookupResponse.Key(pub_key_X: $0.pub_key_X, pub_key_Y: $0.pub_key_Y, address: $0.address)
Yes. This just maps `KeyLookupResult` to a `LegacyVerifierLookupResponse`

2024-07-22 06:50 UTC, metalurgical commented on Sources/TorusUtils/TorusUtils.swift
> +                LegacyVerifierLookupResponse.Key(pub_key_X: $0.pub_key_X, pub_key_Y: $0.pub_key_Y, address: $0.address)
Then we can change the `KeyLookupResult` to `LegacyVerifierLookupResponse` for `formatLegacyPublicKeyData()`

2024-07-22 08:08 UTC, metalurgical commented on Sources/TorusUtils/TorusUtils.swift
> +                if !(pubNonceResult.x.isEmpty || pubNonceResult.y.isEmpty) {
Have adjusted this to throw.

2024-07-23 05:27 UTC, himanshuchawla009 approved these changes

2024-07-24 05:49 UTC, merged